version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3002:5000'
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    command: yarn start

  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
